---
- name: Get information of target entitlements.
 
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/global.yml
  
  tasks:
    - name: Get ACTIVE Entitlements List
      fortinet.fortiflexvm.fortiflexvm_entitlements_list_info:
        username: "{{ fortiflex_username }}"
        password: "{{ fortiflex_password }}"
        accountId: "{{ fortiflex_accountId }}" 
        programSerialNumber: "{{ fortiflex_SN }}" 
        # configId: 41105
        # status: "ACTIVE"    # "ACTIVE", "STOPPED", "PENDDING", "EXPIRED"
        status: "ACTIVE"

        # Optional filter options
        # description: "you can use description to distinguish entitlements"
        # serialNumber: "XXXXXX0000000000"
        # tokenStatus: "NOTUSED"
      register: result

    - name: Save entitlement info to file on control node
      copy:
        content: "{{ result.entitlements }}"
        dest: /home/fortinet/automation/ansible/fortiflex/entitlements.txt
      delegate_to: localhost

    - name: Place Tokens into Associated Files (via Python script)
      ansible.builtin.script: flex-entitlements-parse.py {{ file_name }} {{ config_id }} {{ lic_location }}
      args:
        executable: python3 # Specify the Python interpreter if needed
      vars:
        file_name: "entitlements.txt"
        lic_location: "/home/fortinet/automation/ansible/fortinet/license"
      register: result

    - name: Display response
      ansible.builtin.debug:
        var: result.stdout_lines
